### ISSUE TITLE
Why current version emacs cannot install this package?

### ISSUE THREAD

**Issue by jadestrong** [mallt/mysql-to-org-mode#3]
This is so cool. Is there need any update? I really want to try it!

**Comment by mallt** [comment]
Which version of emacs are you using?

**Comment by jadestrong** [comment]
Version 25.2 (9.0) on Mac   package-install cannot find this package

**Comment by mallt** [comment]
If you have added `melpa` to the `package-archives` variable you should be able to install it:
`(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)`

If it's not shown after running `M-x` `package-install`, that might indicate it has already been installed. If you run `M-x` `list-packages` you can check if the package is available or already installed by searching for `mysql-to-org` in the `*Packages*` buffer.

**Comment by jadestrong** [comment]
I found it in `*Packages*`,  so I delete it and reinstalled, now it works. TKU

**Comment by mallt** [comment]
Ok great!
