### ISSUE TITLE
Table format

### ISSUE THREAD

**Issue by tworthington** [mallt/mysql-to-org-mode#4]
C-c C-m e and C-c C-m p both produce tables which org claims are "table.el" tables. None of the normal org-table shortcuts for moving/adding rows/columns will work on them. Basically, the corner pluses need to become bars.

**Comment by mallt** [comment]
The org-table functions should work correctly. Which version of emacs and org-mode are you using? I'll try to test on your setup.

**Comment by tworthington** [comment]
Emacs 25.3.2 and Org 9.1.6

**Comment by mallt** [comment]
I tested the org-table-move-row and -column functions on emacs 25.3.2 and they seem to work correctly here:
![mysql-to-org-emacs-25-3-org-table-move](https://user-images.githubusercontent.com/8885691/34897650-7119d574-f7ef-11e7-9ee5-56ea438a44df.gif)

Can you maybe post a screenshot of a table as you see it? There must be something wrong with the format if the org-table-move functions are not working.

**Comment by tworthington** [comment]
Here's a screenshot of my results. Basically, the top row has +'s instead of bars at each end, as does the separator row.
![screenshot at 2018-01-23 08 11 37](https://user-images.githubusercontent.com/3090825/35264610-50590a2a-0015-11e8-8c9f-693532d9db9e.png)

**Comment by mallt** [comment]
Thanks for the screenshot. I notice you are using mariadb, I will check if that is causing the problem.

**Comment by mallt** [comment]
I added support for MariaDB in the latest commit. Could you check if your problem is solved after installing the latest melpa version of the package (20180123.714)? Thanks!

**Comment by tworthington** [comment]
Perfect! I'd almost forgotten I'd switched to Maria.Thank you very much.

Thomas

**Comment by mallt** [comment]
Ok great, you're welcome!
