### ISSUE TITLE
Completion?

### ISSUE THREAD

**Issue by tworthington** [mallt/mysql-to-org-mode#5]
C-c C-m s opens a scratch buffer but using C-c TAB opens another buffer called *SQL* rather than producing any sort of completion prompt.

Once *SQL* is open results are sent to it instead of mysql-to-org-output.

**Comment by mallt** [comment]
C-c TAB is linked to the function `sql-product-interactive`. This is a function of the default emacs sql package and is not a keybinding that is linked to completions.

To access the completions provided by `mysql-to-org`, you can use `company-mode` or another completion package that loads candidates provided by the `completion-at-point-functions`.

Which completion package are you currently using?

**Comment by tworthington** [comment]
Right, the C-c TAB was a mistake from mis-reading a help buffer, so ignore that.

If I open a new buffer and put it in SQL mode and turn on company mode, I get some completion now, but it's very limited - basically the same as dabbrev-expand as far as I can tell. However, once I turn on mysql-to-org mode, anywhere I would expect completion I get an error in the minibuffer saying

    Company: backend company-capf error "Invalid function: (bounds (bounds-of-thing-at-point (quote symbol)))" with args (prefix)

Do I need to set up a backend or anything first?

**Comment by mallt** [comment]
I will try to reproduce the error. Which version of company-mode are you using? (you can check this with `M-x company-version`)

**Comment by tworthington** [comment]
0.9.4

**Comment by mallt** [comment]
Could you try starting emacs with the `-q` option, then go to the scratch buffer and evaluate the following lines:
```
(package-initialize)
(require 'company)
(require 'mysql-to-org)
```

If you then do `M-x mysql-to-org-scratch` followed by `M-x company-mode`, are you then able to get completions for table and column names without the `Invalid function` error of the `company-capf` backend?

These steps should rule out interference from any local configurations.

Thanks for checking!

**Comment by tworthington** [comment]
Hi,
  Got the same error message as above (Company: backend company-capf error ...)

**Comment by mallt** [comment]
Ok, thanks for testing! 

I'm not sure what's causing this `company-capf` error. Did you perhaps recently upgrade to emacs 25 from an older emacs version? Mysql-to-org is using the `when-let` macro which is available only since emacs 25, so if you recently upgraded your emacs version you might need to recompile your elpa packages by running `(byte-recompile-directory package-user-dir nil 'force)`.

**Comment by tworthington** [comment]
Finally had time to try this and it worked! Completion is now available, although the output still isn't an Org table (see other bug report with screenshot).

**Comment by mallt** [comment]
Ok great! I'll close this issue then.
